-- ASPM/CTEM Platform — MySQL Schema
-- Run: node migrations/run.js

CREATE TABLE IF NOT EXISTS cpr_scores (
  id            CHAR(36)      NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id        VARCHAR(100)  NOT NULL UNIQUE,
  app_name      VARCHAR(200)  NOT NULL,
  business_unit VARCHAR(200),
  domain        VARCHAR(200),
  asset_criticality ENUM('critical','high','medium','low') DEFAULT 'medium',
  env_score     DECIMAL(5,2)  DEFAULT 0,
  vuln_score    DECIMAL(5,2)  DEFAULT 0,
  cpr_score     DECIMAL(5,2)  DEFAULT 5,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_weightages (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  report_type VARCHAR(50)  NOT NULL UNIQUE,
  label       VARCHAR(200),
  weightage   DECIMAL(4,1) NOT NULL DEFAULT 5,
  max_weight  DECIMAL(4,1) DEFAULT 8,
  enabled     TINYINT(1)   DEFAULT 1,
  updated_by  VARCHAR(100),
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ingestion_history (
  id            CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  report_type   VARCHAR(50)  NOT NULL,
  source_type   ENUM('file_upload','api_sync','oracle_sync') NOT NULL DEFAULT 'file_upload',
  file_name     VARCHAR(500),
  file_size     BIGINT,
  uploaded_by   VARCHAR(100) DEFAULT 'system',
  total_records INT          DEFAULT 0,
  inserted      INT          DEFAULT 0,
  failed        INT          DEFAULT 0,
  status        ENUM('pending','processing','success','partial','failed') DEFAULT 'pending',
  error_log     JSON,
  started_at    TIMESTAMP    NULL,
  completed_at  TIMESTAMP    NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS integration_configs (
  id               CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  name             VARCHAR(200) NOT NULL,
  report_type      VARCHAR(50)  NOT NULL,
  tool             VARCHAR(100),
  endpoint_url     VARCHAR(500),
  auth_type        ENUM('api_key','oauth2','basic','bearer') DEFAULT 'api_key',
  credentials      JSON,
  poll_interval    ENUM('hourly','daily','weekly','manual') DEFAULT 'daily',
  poll_cron        VARCHAR(100),
  enabled          TINYINT(1)  DEFAULT 1,
  last_sync_at     TIMESTAMP   NULL,
  last_sync_status ENUM('success','failed','running','never_run') DEFAULT 'never_run',
  last_sync_count  INT         DEFAULT 0,
  last_error       TEXT,
  custom_params    JSON,
  created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS app_posture_scores (
  id                    CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id                VARCHAR(100) NOT NULL UNIQUE,
  app_name              VARCHAR(200) NOT NULL,
  business_unit         VARCHAR(200),
  domain                VARCHAR(200),
  asset_criticality     ENUM('critical','high','medium','low') DEFAULT 'medium',
  sast_norm_score       DECIMAL(5,2) DEFAULT 0,
  dast_norm_score       DECIMAL(5,2) DEFAULT 0,
  sca_norm_score        DECIMAL(5,2) DEFAULT 0,
  va_norm_score         DECIMAL(5,2) DEFAULT 0,
  bas_norm_score        DECIMAL(5,2) DEFAULT 0,
  cart_norm_score       DECIMAL(5,2) DEFAULT 0,
  waf_norm_score        DECIMAL(5,2) DEFAULT 0,
  ips_norm_score        DECIMAL(5,2) DEFAULT 0,
  fw_norm_score         DECIMAL(5,2) DEFAULT 0,
  siem_norm_score       DECIMAL(5,2) DEFAULT 0,
  pt_ext_norm_score     DECIMAL(5,2) DEFAULT 0,
  pt_int_norm_score     DECIMAL(5,2) DEFAULT 0,
  pt_mobile_norm_score  DECIMAL(5,2) DEFAULT 0,
  red_team_norm_score   DECIMAL(5,2) DEFAULT 0,
  audit_norm_score      DECIMAL(5,2) DEFAULT 0,
  os_comp_norm_score    DECIMAL(5,2) DEFAULT 0,
  db_comp_norm_score    DECIMAL(5,2) DEFAULT 0,
  new_app_security_score DECIMAL(5,2) DEFAULT 0,
  cpr_score             DECIMAL(5,2) DEFAULT 0,
  final_posture_score   DECIMAL(5,2) DEFAULT 0,
  reports_assessed      JSON,
  reports_not_assessed  JSON,
  coverage_percentage   DECIMAL(5,2) DEFAULT 0,
  total_critical        INT DEFAULT 0,
  total_high            INT DEFAULT 0,
  total_medium          INT DEFAULT 0,
  total_low             INT DEFAULT 0,
  total_open            INT DEFAULT 0,
  last_computed_at      TIMESTAMP NULL,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS score_history (
  id                     CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id                 VARCHAR(100) NOT NULL,
  snapshot_date          DATE        NOT NULL,
  new_app_security_score DECIMAL(5,2),
  cpr_score              DECIMAL(5,2),
  final_posture_score    DECIMAL(5,2),
  total_critical         INT,
  total_high             INT,
  coverage_percentage    DECIMAL(5,2),
  created_at             TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_app_date (app_id, snapshot_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sast_findings (
  id                 CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id             VARCHAR(100),
  app_name           VARCHAR(200),
  tool               VARCHAR(50),
  scan_date          DATE,
  rule_id            VARCHAR(100),
  file_path          VARCHAR(500),
  line_number        INT,
  vulnerability_type VARCHAR(200),
  cwe_id             VARCHAR(20),
  severity           ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'low',
  severity_score     DECIMAL(4,1),
  title              VARCHAR(500),
  description        TEXT,
  remediation        TEXT,
  status             ENUM('open','in_progress','resolved','accepted_risk','false_positive') DEFAULT 'open',
  ingestion_id       CHAR(36),
  raw_data           JSON,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_app_id (app_id),
  INDEX idx_severity (severity),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dast_findings (
  id           CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id       VARCHAR(100),
  app_name     VARCHAR(200),
  tool         VARCHAR(50),
  scan_date    DATE,
  alert_type   VARCHAR(200),
  cwe_id       VARCHAR(20),
  affected_url VARCHAR(1000),
  http_method  VARCHAR(10),
  parameter    VARCHAR(200),
  attack       TEXT,
  evidence     TEXT,
  severity     ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'low',
  severity_score DECIMAL(4,1),
  title        VARCHAR(500),
  description  TEXT,
  solution     TEXT,
  status       ENUM('open','in_progress','resolved','accepted_risk','false_positive') DEFAULT 'open',
  ingestion_id CHAR(36),
  raw_data     JSON,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_app_id (app_id),
  INDEX idx_severity (severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sca_findings (
  id              CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id          VARCHAR(100),
  app_name        VARCHAR(200),
  tool            VARCHAR(50),
  scan_date       DATE,
  library_name    VARCHAR(300),
  library_version VARCHAR(50),
  cve_id          VARCHAR(50),
  cvss_score      DECIMAL(4,1),
  severity        ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'low',
  severity_score  DECIMAL(4,1),
  title           VARCHAR(500),
  description     TEXT,
  fixed_version   VARCHAR(50),
  status          ENUM('open','in_progress','resolved','accepted_risk') DEFAULT 'open',
  ingestion_id    CHAR(36),
  raw_data        JSON,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_app_id (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bas_findings (
  id               CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id           VARCHAR(100),
  app_name         VARCHAR(200),
  tool             VARCHAR(50),
  simulation_date  DATE,
  technique_id     VARCHAR(50),
  tactic           VARCHAR(100),
  kill_chain_phase VARCHAR(100),
  title            VARCHAR(500),
  description      TEXT,
  result           ENUM('success','partial','failed','blocked') DEFAULT 'success',
  severity         ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'medium',
  severity_score   DECIMAL(4,1),
  affected_asset   VARCHAR(200),
  status           ENUM('open','in_progress','resolved') DEFAULT 'open',
  ingestion_id     CHAR(36),
  raw_data         JSON,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_app_id (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cart_findings (
  id              CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  app_id          VARCHAR(100),
  app_name        VARCHAR(200),
  assessment_date DATE,
  readiness_area  VARCHAR(200),
  control_domain  VARCHAR(200),
  control_id      VARCHAR(50),
  title           VARCHAR(500),
  description     TEXT,
  gap             TEXT,
  severity        ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'medium',
  severity_score  DECIMAL(4,1),
  recommendation  TEXT,
  status          ENUM('open','in_progress','resolved') DEFAULT 'open',
  ingestion_id    CHAR(36),
  raw_data        JSON,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS firewall_rules (
  id              CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  vendor          ENUM('palo_alto','fortinet','checkpoint','other') NOT NULL,
  import_date     DATE,
  documentation   VARCHAR(500),
  rule_num        INT,
  from_zone       VARCHAR(200),
  source          TEXT,
  to_zone         VARCHAR(200),
  destination     TEXT,
  service         TEXT,
  action          VARCHAR(30),
  enabled         TINYINT(1)  DEFAULT 1,
  rule_name       VARCHAR(200),
  log_enabled     TINYINT(1)  DEFAULT 1,
  comment         TEXT,
  application     TEXT,
  user_field      VARCHAR(200),
  schedule        VARCHAR(100),
  tag             TEXT,
  profile         VARCHAR(200),
  url_category    TEXT,
  vpn             VARCHAR(200),
  section_header  VARCHAR(200),
  layer_name      VARCHAR(200),
  layer_type      VARCHAR(100),
  layer_uid       VARCHAR(100),
  rule_position   INT,
  parent_rule_uid VARCHAR(100),
  risk_score      DECIMAL(6,2) DEFAULT 0,
  risk_flags      JSON,
  is_permissive   TINYINT(1)   DEFAULT 0,
  is_undocumented TINYINT(1)   DEFAULT 0,
  is_no_log       TINYINT(1)   DEFAULT 0,
  is_shadow       TINYINT(1)   DEFAULT 0,
  hit_count       INT,
  ingestion_id    CHAR(36),
  raw_data        JSON,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_vendor (vendor),
  INDEX idx_risk_score (risk_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS waf_rules (
  id               CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  vendor           VARCHAR(50),
  app_id           VARCHAR(100),
  app_name         VARCHAR(200),
  rule_id          VARCHAR(100),
  rule_name        VARCHAR(300),
  rule_type        VARCHAR(100),
  pattern          TEXT,
  action           VARCHAR(30),
  enabled          TINYINT(1)  DEFAULT 1,
  exception_count  INT         DEFAULT 0,
  exceptions       JSON,
  whitelist_entries JSON,
  whitelist_count  INT         DEFAULT 0,
  severity         VARCHAR(20),
  gap_identified   TINYINT(1)  DEFAULT 0,
  gap_description  TEXT,
  import_date      DATE,
  ingestion_id     CHAR(36),
  raw_data         JSON,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ips_signatures (
  id           CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  vendor       VARCHAR(50),
  sig_id       VARCHAR(100),
  sig_name     VARCHAR(300),
  category     VARCHAR(100),
  severity     VARCHAR(20),
  action       VARCHAR(30),
  enabled      TINYINT(1)  DEFAULT 1,
  protocol     VARCHAR(20),
  cve_references JSON,
  description  TEXT,
  policy_name  VARCHAR(200),
  gap_flag     TINYINT(1)  DEFAULT 0,
  gap_reason   VARCHAR(500),
  import_date  DATE,
  ingestion_id CHAR(36),
  raw_data     JSON,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS siem_incidents (
  id                         CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  incident_id                VARCHAR(100) UNIQUE,
  ciso_incident_coordinator  VARCHAR(200),
  date_created               DATETIME,
  days_open                  INT,
  days_to_resolve            INT,
  incident_details           TEXT,
  incident_coordinator       VARCHAR(200),
  incident_status            VARCHAR(50),
  incident_summary           TEXT,
  incident_validated_by      VARCHAR(200),
  justification              TEXT,
  kill_chain                 VARCHAR(200),
  source                     VARCHAR(200),
  team                       VARCHAR(200),
  threat_category            VARCHAR(200),
  title                      VARCHAR(500),
  validation_remarks         TEXT,
  date_assigned              DATETIME,
  date_closed                DATETIME,
  date_resolved              DATETIME,
  dest_hostname              VARCHAR(200),
  dest_ip                    VARCHAR(50),
  dest_port                  INT,
  incident_owner             VARCHAR(200),
  overall_status             VARCHAR(50),
  priority                   VARCHAR(30),
  siem_rule_enhancements     TEXT,
  source_hostname            VARCHAR(200),
  criticality                VARCHAR(50),
  closure_remark             TEXT,
  to_be_blocked              TINYINT(1)  DEFAULT 0,
  sla_breached               TINYINT(1)  DEFAULT 0,
  risk_score                 DECIMAL(6,2) DEFAULT 0,
  app_id                     VARCHAR(100),
  ingestion_id               CHAR(36),
  raw_data                   JSON,
  created_at                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_priority (priority),
  INDEX idx_sla (sla_breached)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pt_findings (
  id                  CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  pt_type             ENUM('external_webapp','internal_webapp','mobile','api') NOT NULL,
  app_id              VARCHAR(100),
  app_name            VARCHAR(200),
  engagement_id       VARCHAR(100),
  engagement_date     DATE,
  assessor_name       VARCHAR(200),
  finding_title       VARCHAR(500),
  description         TEXT,
  vulnerability_class VARCHAR(100),
  owasp_category      VARCHAR(100),
  owasp_mobile_cat    VARCHAR(100),
  cwe_id              VARCHAR(20),
  cve_id              VARCHAR(50),
  cvss_score          DECIMAL(4,1),
  severity            ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'medium',
  severity_score      DECIMAL(4,1),
  affected_url        VARCHAR(1000),
  affected_parameter  VARCHAR(200),
  proof_of_concept    TEXT,
  remediation         TEXT,
  status              ENUM('open','in_progress','resolved','accepted_risk') DEFAULT 'open',
  retest_status       ENUM('not_retested','fixed','persists','partially_fixed'),
  retest_date         DATE,
  platform            ENUM('ios','android','both'),
  app_version         VARCHAR(50),
  jailbreak_required  TINYINT(1),
  network_segment     VARCHAR(100),
  source_ip_range     VARCHAR(200),
  source_type         ENUM('file_upload','oracle_db') DEFAULT 'file_upload',
  ingestion_id        CHAR(36),
  raw_data            JSON,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_app_id (app_id),
  INDEX idx_pt_type (pt_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS red_team_findings (
  id              CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  engagement_id   VARCHAR(100),
  engagement_date DATE,
  engagement_type ENUM('red_team','purple_team','threat_hunting','tabletop') DEFAULT 'red_team',
  app_id          VARCHAR(100),
  app_name        VARCHAR(200),
  technique_id    VARCHAR(50),
  technique_name  VARCHAR(300),
  tactic          VARCHAR(100),
  sub_technique   VARCHAR(100),
  finding_title   VARCHAR(500),
  description     TEXT,
  affected_asset  VARCHAR(200),
  evidence        TEXT,
  severity        ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'high',
  severity_score  DECIMAL(4,1),
  detection_gap   TINYINT(1)  DEFAULT 0,
  prevention_gap  TINYINT(1)  DEFAULT 0,
  remediation     TEXT,
  status          ENUM('open','in_progress','resolved') DEFAULT 'open',
  ingestion_id    CHAR(36),
  raw_data        JSON,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_findings (
  id                  CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  observation_id      VARCHAR(100),
  audit_type          ENUM('internal','external','regulatory','iso','rbi','sebi','cert_in') DEFAULT 'internal',
  audit_date          DATE,
  app_id              VARCHAR(100),
  app_name            VARCHAR(200),
  business_unit       VARCHAR(200),
  observation_title   VARCHAR(500),
  observation_desc    TEXT,
  severity            ENUM('critical','high','medium','low','informational') NOT NULL DEFAULT 'medium',
  severity_score      DECIMAL(4,1),
  repeat_finding      TINYINT(1)  DEFAULT 0,
  due_date            DATE,
  owner               VARCHAR(200),
  management_response TEXT,
  action_plan         TEXT,
  status              ENUM('open','in_progress','closed','overdue') DEFAULT 'open',
  ingestion_id        CHAR(36),
  raw_data            JSON,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS os_compliance_findings (
  id                   CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  asset_id             VARCHAR(100),
  hostname             VARCHAR(200),
  ip_address           VARCHAR(50),
  os_type              VARCHAR(100),
  os_version           VARCHAR(100),
  scan_date            DATE,
  benchmark_standard   VARCHAR(100),
  control_id           VARCHAR(50),
  control_description  VARCHAR(1000),
  compliance_status    ENUM('pass','fail','not_applicable','error') NOT NULL,
  current_value        VARCHAR(500),
  expected_value       VARCHAR(500),
  severity             ENUM('critical','high','medium','low','informational'),
  severity_score       DECIMAL(4,1),
  remediation          TEXT,
  exception_status     ENUM('no_exception','approved','pending') DEFAULT 'no_exception',
  source_type          ENUM('file_upload','oracle_db') DEFAULT 'file_upload',
  ingestion_id         CHAR(36),
  raw_data             JSON,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_asset (asset_id),
  INDEX idx_status (compliance_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS db_compliance_findings (
  id                   CHAR(36)    NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  asset_id             VARCHAR(100),
  db_hostname          VARCHAR(200),
  db_type              ENUM('oracle','mssql','mysql','postgresql','mongodb','other'),
  db_version           VARCHAR(100),
  db_instance_name     VARCHAR(100),
  ip_address           VARCHAR(50),
  scan_date            DATE,
  benchmark_standard   VARCHAR(100),
  control_id           VARCHAR(50),
  control_description  VARCHAR(1000),
  compliance_status    ENUM('pass','fail','not_applicable','error') NOT NULL,
  current_value        VARCHAR(500),
  expected_value       VARCHAR(500),
  severity             ENUM('critical','high','medium','low','informational'),
  severity_score       DECIMAL(4,1),
  remediation          TEXT,
  exception_status     ENUM('no_exception','approved','pending') DEFAULT 'no_exception',
  source_type          ENUM('file_upload','oracle_db') DEFAULT 'file_upload',
  ingestion_id         CHAR(36),
  raw_data             JSON,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_asset (asset_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
